### ISSUE TITLE
Document specific windows build setup in meta.yaml

### ISSUE THREAD

**Issue by bobleesj** [conda-forge/diffpy.pdffit2-feedstock#28]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Instead of writing it somewhere on Gitlab/GitHub, include the specific `meta.yml` setup info required for building windows investigated here https://github.com/conda-forge/diffpy.pdffit2-feedstock/pull/27 

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by bobleesj** [comment]
closed - the following setup works for `windows`, `linux`, and `macOS non arm64`

```
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - gsl {{ gsl }} 
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning >=2.0
    - gsl {{ gsl }} 
  run:
    - python
    - setuptools
    - diffpy.structure
```
